name: Deploy Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install NPM dependencies
      run: cd App && npm install

    - name: Build project
      run: cd App && npm run android:build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: App/android/app/build/outputs/apk/release/app-release.apk
  
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: android
  
