name: Deploy Android

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'

    - name: Install NPM dependencies
      run: cd App && npm ci

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      id: cache-primes
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('App/package-lock.json') }}

  build:
    name: Build Android
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('App/ppackage-lock.json') }}

    - name: Build code
      run: cd App && npm run android:build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: App/android/app/build/outputs/apk/release/app-release.apk

    - name: Create release
      uses: actions/create-release@v1
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Publish release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: App/android/app/build/outputs/apk/release/app-release.apk
        asset_name: android.apk
        asset_content_type: octet-stream