name: Deploy application

on:
  push:
    branches:
      - main

env:
  path: App

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app.outputs.value }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install NPM dependencies
      run: cd ${{ env.path }} && npm ci

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.path }}/node_modules
        key: node-${{ hashFiles('${{ env.path }}/package-lock.json') }}

    - name: Get minimum version
      id: minimum_version
      run: echo "value=`cd App && npm pkg get version`" >> "$GITHUB_OUTPUT"

    - name: Get current version
      uses: reecetech/version-increment@2023.4.1
      id: current_version
      with:
        scheme: semver
        increment: patch

    - name: Set new version
      id: app
      run: echo "value=`./version_manager.sh ${{ steps.minimum_version.outputs.value }} ${{ steps.current_version.outputs.current-version }}`" >> "$GITHUB_OUTPUT"

  android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.path }}/node_modules
        key: node-${{ hashFiles('${{ env.path }}/package-lock.json') }}

    - name: Set app version
      run: cd ${{ env.path }} && npm pkg set version=${{ needs.setup.outputs.version }}

    - name: Build code
      run: cd ${{ env.path }} && npm run android:build -- -PversionName=${{ needs.setup.outputs.version }} -PversionCode=${{ github.run_number }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: ${{ env.path }}/android/app/build/outputs/apk/release/app-release.apk

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [setup, android]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: android

    - name: Create release
      uses: actions/create-release@v1
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ needs.setup.outputs.version }}
        tag_name: ${{ needs.setup.outputs.version }}
        draft: false
        prerelease: false

    - name: Publish release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: app-release.apk
        asset_name: cronos-${{ needs.setup.outputs.version }}.apk
        asset_content_type: octet-stream